services:
  db:
    image: postgres:16
    container_name: parcial-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"   # 5433 en tu PC para no chocar con un Postgres local
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: parcial-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/appdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: cambia-esta-clave-super-secreta-de-al-menos-32-bytes-123456
    ports:
      - "8080:8080"

volumes:
  pgdata:
